[package]
name = "synapse_cli"
version = "0.2.0"
edition = "2024"
license = "MIT"
readme = "README.md"
description = ""

[[bin]]
name = "synapse"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.4", features = ["derive"]}
regex = "1.10"
